### ISSUE TITLE
webhook_url's wrong when using absolute url in config/cashier.php

### ISSUE THREAD

**Issue by michelterstege81** [mollie/laravel-cashier-mollie#177]
I'm currently testing with ngrok and specify the webhook url's as absolute url's as seems possible looking into the comment in the config file.

.env
```
NGROK_URL="https://83da-89-205-136-216.ngrok-free.app"
```

config/cashier.php
```
/**
  * The default aftercare webhook url is called by Mollie on refunds and chargebacks. You can use either a relative or
  * absolute url.
  */
 'aftercare_webhook_url' => env('NGROK_URL') ? env('NGROK_URL').'/webhooks/mollie/aftercare' : 'webhooks/mollie/aftercare',
```

When creating a new subscription in my controller like this:
```
$result = $tenant->newSubscription($name, $request->plan)
                        ->trialDays(config('saas.trial_days'))
                        ->create();
```

I get redirected to Mollie. And back after payment.

(without the ngrok url I get an error back from mollie that the webhook is unreachable. This is expected).

So far nothing wrong. Then however mollie calls the webhook and things go wrong.

In FirstPaymentWebhookController the handleWebhook method goes wrong.

Looking into vendor/mollie/laravel-cashier-mollie/src/Cashier.php (when adding some logging) you can see that the domain is stripped:
```
/**
     * Get the aftercare webhook relative url.
     *
     * @return string
     */
    public static function aftercareWebhookUrl()
    {
        Log::debug('aftercareWebhookUrl '.config('cashier.aftercare_webhook_url'));
        Log::debug('pathFromUrl '.self::pathFromUrl(config('cashier.aftercare_webhook_url')));

        return self::pathFromUrl(config('cashier.aftercare_webhook_url'));
    }
```

gives:
```
[2023-06-16 15:23:00] local.DEBUG: aftercareWebhookUrl https://83da-89-205-136-216.ngrok-free.app/webhooks/mollie/aftercare  
[2023-06-16 15:23:00] local.DEBUG: pathFromUrl webhooks/mollie/aftercare  
```

In FirstPaymentWebhookController handleWebhook this then results in:
```
$payment->webhookUrl = route('webhooks.mollie.aftercare');
```

```
http://ip-portal.test/webhooks/mollie/aftercare
```

This comes from APP_URL in .env to 'ip-portal.test' domain.

This results in an error:

```
[2023-06-16 15:36:02] local.DEBUG: WEBHOOK_URL http://ip-portal.test/webhooks/mollie/aftercare  
[2023-06-16 15:36:02] local.ERROR: [2023-06-16T15:36:02+0000] Error executing API call (422: Unprocessable Entity): The webhook URL is invalid because it is unreachable from Mollie's point of view.. Field: webhookUrl. Documentation: https://docs.mollie.com/reference/v2/payments-api/update-payment {"exception":"[object] (Mollie\\Api\\Exceptions\\ApiException(code: 422): [2023-06-16T15:36:02+0000] Error executing API call (422: Unprocessable Entity): The webhook URL is invalid because it is unreachable from Mollie's point of view.. Field: webhookUrl. Documentation: https://docs.mollie.com/reference/v2/payments-api/update-payment at C:\\xampp\\htdocs\\IP Portal\\laravel-ip-portal\\vendor\\mollie\\mollie-api-php\\src\\Exceptions\\ApiException.php:114)
[stacktrace]
#0 C:\\xampp\\htdocs\\IP Portal\\laravel-ip-portal\\vendor\\mollie\\laravel-mollie\\src\\MollieLaravelHttpClientAdapter.php(44): Mollie\\Api\\Exceptions\\ApiException::createFromResponse(Object(GuzzleHttp\\Psr7\\Response), NULL)
#1 C:\\xampp\\htdocs\\IP Portal\\laravel-ip-portal\\vendor\\mollie\\laravel-mollie\\src\\MollieLaravelHttpClientAdapter.php(23): Mollie\\Laravel\\MollieLaravelHttpClientAdapter->parseResponseBody(Object(Illuminate\\Http\\Client\\Response))
#2 C:\\xampp\\htdocs\\IP Portal\\laravel-ip-portal\\vendor\\mollie\\mollie-api-php\\src\\MollieApiClient.php(673): Mollie\\Laravel\\MollieLaravelHttpClientAdapter->send('PATCH', 'https://api.mol...', Array, '{\"description\":...')
#3 C:\\xampp\\htdocs\\IP Portal\\laravel-ip-portal\\vendor\\mollie\\mollie-api-php\\src\\MollieApiClient.php(617): Mollie\\Api\\MollieApiClient->performHttpCallToFullUrl('PATCH', 'https://api.mol...', '{\"description\":...')
#4 C:\\xampp\\htdocs\\IP Portal\\laravel-ip-portal\\vendor\\mollie\\mollie-api-php\\src\\Endpoints\\EndpointAbstract.php(100): Mollie\\Api\\MollieApiClient->performHttpCall('PATCH', 'payments/tr_FmV...', '{\"description\":...')
#5 C:\\xampp\\htdocs\\IP Portal\\laravel-ip-portal\\vendor\\mollie\\mollie-api-php\\src\\Endpoints\\PaymentEndpoint.php(72): Mollie\\Api\\Endpoints\\EndpointAbstract->rest_update('tr_FmVZ9S5NJq', Array)
#6 C:\\xampp\\htdocs\\IP Portal\\laravel-ip-portal\\vendor\\mollie\\mollie-api-php\\src\\Resources\\Payment.php(707): Mollie\\Api\\Endpoints\\PaymentEndpoint->update('tr_FmVZ9S5NJq', Array)
#7 C:\\xampp\\htdocs\\IP Portal\\laravel-ip-portal\\vendor\\mollie\\laravel-cashier-mollie\\src\\Mollie\\UpdateMolliePayment.php(14): Mollie\\Api\\Resources\\Payment->update()
#8 C:\\xampp\\htdocs\\IP Portal\\laravel-ip-portal\\vendor\\mollie\\laravel-cashier-mollie\\src\\Http\\Controllers\\FirstPaymentWebhookController.php(35): Laravel\\Cashier\\Mollie\\UpdateMolliePayment->execute(Object(Mollie\\Api\\Resources\\Payment))
#9 C:\\xampp\\htdocs\\IP Portal\\laravel-ip-portal\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(46): Laravel\\Cashier\\Http\\Controllers\\FirstPaymentWebhookController->handleWebhook(Object(Illuminate\\Http\\Request))
#10 C:\\xampp\\htdocs\\IP Portal\\laravel-ip-portal\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Cashier\\Http\\Controllers\\FirstPaymentWebhookController), 'handleWebhook')
```

Unfortunately I cannot change APP_URL to the url provided by NGROK, since that is a subdomain and I use dynamic subdomains for my tenants. It's a multi tenant application.

I think the package should check if an absolute url is used in the config and if so not modify it.

**Comment by iqfx** [comment]
I had the same issue, try setting the webhook url from within the plan by using the setFirstPaymentWebhookUrl() function.

Personally my subscriptions plans are a little more complicated as I'm using a custom DatabasePlanRepository with a custom model so that they can be stored and retrieved from the database. But in short i overwrote the firstPaymentWebhookUrl() function.

It now looks like this:

```
    public function firstPaymentWebhookUrl()
    {
        return env("NGROK_LINK") ? env("NGROK_LINK") : route('webhooks.mollie');
    }
```
the official implementation can be found in` Laravel\Cashier\Plan\Plan` and the contract used is `Laravel\Cashier\Plan\Contracts\Plan`
I know this may not be the concrete solution for you but hopefully it will put you on the right track for debugging your issue.

**Comment by Naoray** [comment]
Dear @michelterstege81,

Thank you for sharing your concern!

Regarding laravel-mollie-cashier, our aim is to offer a solution that caters to the needs of the majority of our customers. However, it's important to note that we may not be able to accommodate every customer's requirements due to unique situations like yours. For instance, your specific setup involving tenant subdomains falls into such a category, which we might not have anticipated during development.

In your particular case, we suggest considering the following approach: redeclare the webhook routes and manually associate them with the corresponding controllers. This workaround should enable you to address the issue effectively.

```php
Route::namespace('\Laravel\Cashier\Http\Controllers')->domain(‘your_subdomain’)->group(function () {
    Route::name('webhooks.mollie.default')->post(
        Cashier::webhookUrl(),
        [WebhookController::class, 'handleWebhook']
    );

    Route::name('webhooks.mollie.aftercare')->post(
        Cashier::aftercareWebhookUrl(),
        [AftercareWebhookController::class, 'handleWebhook']
    );

    Route::name('webhooks.mollie.first_payment')->post(
        Cashier::firstPaymentWebhookUrl(),
        [FirstPaymentWebhookController::class, 'handleWebhook']
    );
});
```

**Comment by michelterstege81** [comment]
Hi @Naoray ,

Thanks. I'm actually doing something like that right now. Using that approach and putting that in a domain group, so to make sure the ngrok domain is used when the route() function is called on these routes.

Though I would say it's unexpected behaviour looking at the comment in the config file. I would heave expected that the specified url would always be used.

Looking into the comment above of @iqfx  and issue #141 however I'm not unique in experiencing this issue ;)

**Comment by Naoray** [comment]
Hi @michelterstege81,

I get that the comment in the configuration can be misleading. Although it’s not wrong. You can put in relative or absolute urls and it will simply be able to extract the path from the absolute url.

> Looking into the comment above of @iqfx and issue https://github.com/mollie/laravel-cashier-mollie/issues/141 however I'm not unique in experiencing this issue ;)

Your issue is in a way unique that you use dynamic subdomains per tenant, which doesn’t seem to be the case in #141.

—

I just checked the packages code and saw that we have a `Cashier::ignoreRoutes()` method which you should be able to call in the AppServiceProvider’s register method with `Cashier::ignoreRoutes();`, then you won’t have the routes double defined from the package and your own app.

**Comment by clebuchegger** [comment]
late to the game but still relevant, I will try the suggested workaround.

In general I think this is not consistently solved, as in any dev setup I still want my APP_URL to be my local / docker URL and my webhook some expose/ngrok URL.

in addition I found at least one point in the code where the given URL is used (this might be why the first payment works, but the aftercare webhook then doesn't?)
see src/Order/Order.php 240:
`$payment = (new MandatedPaymentBuilder(
                        $owner,
                        $this->getDescription(),
                        $totalDue,
                        url(config('cashier.webhook_url')),
                        [
                            'metadata' => [
                                'temporary_mollie_payment_id' => $this->mollie_payment_id,
                            ],
                        ]
                    ))->create();`

either way this inconsistency should be solved or clearly marked/commented in the config/cashier.php
